apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: event-manager-backend
  app.kubernetes.io/name: event-manager-backend
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: event-manager

resources:
  - deployment.yml
  - service.yml
