name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Login to AWS ECR
        id: ecr-login
        uses: thalesvon/ecr-login@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_OUTPUT: json
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: 'get-login --no-include-email --region ${AWS_REGION}'
      - name: 'Docker Login'
        run: ${{ steps.ecr-login.outputs.login-string }}
      - name: Build the Docker image
        run: |
          docker pull $DOCKER_IMAGE:latest || true
          docker build . --file Dockerfile --tag $DOCKER_IMAGE:$DOCKER_TAG --tag $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:$DOCKER_TAG
          docker push $DOCKER_IMAGE:latest
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          DOCKER_TAG: ${{ github.sha }}
