name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker pull $DOCKER_IMAGE:latest || true
          docker build . --file Dockerfile --tag $DOCKER_IMAGE:$DOCKER_TAG --tag $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:$DOCKER_TAG
          docker push $DOCKER_IMAGE:latest
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          DOCKER_TAG: ${{ github.sha }}
