name: Elixir Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.2-slim
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Linter
      run: mix credo
